# Generated by Django 5.2 on 2025-05-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGEAweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_insc', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MAEST', 'Maestra'), ('ALUM', 'Alumno')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_insc', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('asistencia', models.BooleanField(default=False)),
                ('alumnos', models.ManyToManyField(related_name='maestras', to='PGEAweb.alumno')),
                ('tipo_danza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PGEAweb.tipodanza')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_maestra', to='PGEAweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('time', models.TimeField()),
                ('alumnos', models.ManyToManyField(to='PGEAweb.alumno')),
                ('maestra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PGEAweb.maestra')),
                ('tipo_danza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGEAweb.tipodanza')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_danza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PGEAweb.tipodanza'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to='PGEAweb.usuario'),
        ),
    ]
