# Generated by Django 5.2 on 2025-05-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGEAweb', '0002_alumno_tipodanza_usuario_maestra_clase_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
